### ISSUE TITLE
How to apply margins between pages?

### ISSUE THREAD

**Issue by RadomirNowak** [react-pdf-viewer/react-pdf-viewer#1157]
Hi there!
I was wondering about the proper way to apply a margin between pages. My approach was to add margin to `rpv-core__inner-page` class, but that does not seem to work (page navigation gets broken). At the moment, when I render my PDF i get very little space between pages (see screenshot)
![image](https://user-images.githubusercontent.com/11005257/172594808-fd5cea71-77e3-47d1-bf91-49ab8a7c3197.png)

Thanks in advance!

**Comment by phuoc-ng** [comment]
It's not possible with the latest version. Making no spaces between pages will ensure the scrolling/zooming work perfectly.
You can try to override the following styles

```css
.rpv-core__page-layer::after {
    bottom: 0.5rem;
    left: 0.5rem;
    right: 0.5rem;
    top: 0.5rem;
}
```
