### ISSUE TITLE
Change the default width of a sidebar tab

### ISSUE THREAD

**Issue by gvtrindade** [react-pdf-viewer/react-pdf-viewer#1713]
Hi, a couldn't find anywhere in the documentation any information about setting the default width of a sidebar tab. Is it possible? If this is not the channel to ask this kind of question, I apologize and kindly ask to be redirected to the place where it can be.

Thanks in advance,
Gabriel Trindade

**Comment by phuocng** [comment]
@gvtrindade You have the ability to customize the `rpv-default-layout__sidebar--opened` CSS class, which controls the appearance of the sidebar when it's open. 

```css
.rpv-default-layout__sidebar--opened {
  width: 12rem;
}
```

Keep in mind that the width of the sidebar will change depending on the width of the screen, so you may need to adjust the width accordingly.

```css
@media (min-width: 768px) {
    .rpv-default-layout__sidebar--opened {
        width: 16rem;
    }
}

@media (min-width: 1024px) {
    .rpv-default-layout__sidebar--opened {
        width: 20rem;
    }
}
```
