### ISSUE TITLE
How to change background color ?

### ISSUE THREAD

**Issue by RedBoardDev** [react-pdf-viewer/react-pdf-viewer#1737]
Hello, I simply want to know how to change the background color. I want to remove it if possible but I don't know where I can find a documentation about style.

**Comment by Vladisdev** [comment]
Same here. Apply styles by class didn't work for me and I also try to find property to apply styles to Viewer component in docs but didin't find one

**Comment by Kentakoong** [comment]
```css
.rpv-thumbnail__container-background-color {
  background-color: var(--color-muted) !important;
}

.rpv-core__inner-page {
  background-color: var(--color-muted) !important;
}
```

did some CSS altering, this worked.

Some more details, you can actually check all the classes on the node modules, on this path, there's all of the root variables, you could copy into your globals.css and use !important to set it

<img width="466" alt="Image" src="https://github.com/user-attachments/assets/481300e9-7069-40fd-9277-332c73f8e05c" />
