### ISSUE TITLE
add custom css

### ISSUE THREAD

**Issue by bylly1** [react-pdf-viewer/react-pdf-viewer#761]
On the dark mode I want to override **rpv-core__inner-page** class  to add _background_ black and **rpv-core__text-layer** to add _background_ black and increase _opacity_. How I do that? Thanks! (p.s: I'm using NextJS)

**Comment by phuoc-ng** [comment]
You can override these CSS class easily.
If you are using NextJS, I assume that the `pages/_app.tsx` looks like

```tsx
/* pages/_app.tsx */

// Import React PDF Viewer styles
import '@react-pdf-viewer/core/lib/styles/index.css';
import '@react-pdf-viewer/default-layout/lib/styles/index.css';

// Your own styles
import '../styles/index.css';
``` 

Then, inside `styles/index.css`, you can override or add more styles to the classes:

```css
/* styles/index.css */
.rpv-core__viewer--dark .rpv-core__inner-page {
   background-color: ...;
}

.rpv-core__viewer--dark .rpv-core__text-layer {
  opacity: ...;
}
```
