### ISSUE TITLE
Fixed Sidebar?

### ISSUE THREAD

**Issue by hkush8289** [react-pdf-viewer/react-pdf-viewer#854]
I want to use the default layout. I have already customized the toolbar, but I want to fix the width of the sidebar. Is this possible?
Thank you

**Comment by phuoc-ng** [comment]
@hkush8289 
You can override the following CSS class:

```css
/* Set the width for opened sidebar */
.rpv-default-layout__sidebar--opened {
    width: 12rem;
}
```
